export const productsENG = [
  {
    id: 1,
    product: "Centrifuge",
    description: "Leica DM500",
    produced: "Germany",
    weight: 6,
    price: 97000,
    material: "Steel",
    category: 'Analysis',
    quantity:1,
    brands: "Flottweg"
  },
  {
    id: 2,
    product: "Spectrophotometer",
    description: "Binder BD56",
    produced: "Germany",
    weight: 34 ,
    price: 125000,
    material: "Aluminum",
    category: 'Research',
    brands: "Rousselet Robatel",
    quantity:1,
  },
  {
    id: 3,
    product: "Dividing Centrifuge",
    description: "Shimadzu UV-1900",
    produced: "Japan",
    weight: 10,
    price: 100000,
    material: "Aluminum",
    category: 'Analysis',
    brands: "Labor-Microscopes",
    quantity:1,
  },
  {
    id: 4,
    product: "Nanocrystalline Microscope",
    description: "Z-1000 Nano",
    produced: "Sweden",
    weight: 8,
    price: 49000,
    material: "Plastic",
    category: 'Research',
    brands: "Flottweg",
    quantity:1,
  },
  {
    id: 5,
    product: "Filtration Centrifuge",
    description: "BioGrow BG-3000",
    produced: "USA",
    weight: 45,
    price: 50000,
    material: "Steel",
    category: 'Analysis',
    brands: "Labor-Microscopes",
    quantity:1,
  },
  {
    id: 6,
    product: "Accelerated Centrifuge",
    description: "LaserSpec LS-2000",
    produced: "China",
    weight: 12 ,
    price: 40000,
    material: "Carbon Fiber",
    category: 'Research',
    brands: "Rousselet Robatel",
    quantity:1,
  },
  {
    id: 7,
    product: "Centrifuge",
    description: "Z-1000Tech",
    produced: "Germany",
    weight: 6 ,
    price: 30000,
    material: "Steel",
    category: 'Research',
    brands: "Rousselet Robatel",
    quantity:1,
  },
  {
    id: 8,
    product: "Telescope",
    description: "Bind-BD5126",
    produced: "Germany",
    weight: 43,
    price: 39000,
    material: "Plastic",
    category: 'Analysis',
    brands: "Labor-Microscopes",
    quantity:1,
  },
  {
    id: 9,
    product: "Dividing Centrifuge",
    description: "KandanUV-100",
    produced: "Japan",
    weight: 10,
    price: 57000,
    material: "Carbon Fiber",
    category: 'Research',
    brands: "Flottweg",
    quantity:1,
  }
];


 export const productsRUS = [
     {
       id:1,
      product: "Центрифуга",
      description: "Leica DM500",
      produced: "Германия",
      weight: 6,
      price: 97000,
      material:"Сталь",
      category:'Анализ',
      quantity:1,
      brands:"Flottweg"
    },
    {
      id:2,
      product: "Спектрофотометр",
      description: "Binder BD56",
      produced: "Германия",
      weight: 34,
      price: 125000,
      material:"Алюминий",
      category:'Исследования',
      brands:"Rousselet Robatel",
      quantity:1,
    },
    {
      id:3,
      product: "Разделительные-цинтрифуга",
      description: "Shimadzu UV-1900",
      produced: "Япония",
      weight: 10,
      price: 100000,
      material:"Алюминий",
      category:'Анализ',
      brands:"Labor-Microscopes",
      quantity:1,
    },
    {
      id:4,
      product: "Нанокристаллический микроскоп",
      description: "Z-1000 Nano",
      produced: "Швеция",
      weight: 8,
      price: 49000,
      material:"Пластик",
      category:'Исследования',
      brands:"Flottweg",
      quantity:1,
    },
    {
      id:5,
      product: "Фильтрационная-цинтрифуга",
      description: "BioGrow BG-3000",
      produced: "США",
      weight: 45,
      price: 50000,
      material:"Сталь",
      category:'Анализ',
      brands:"Labor-Microscopes",
      quantity:1,
    },
    {
      id:6,
      product: "Ускоренная цинтрифуга",
      description: "LaserSpec LS-2000",
      produced: "Китай",
      weight: 12,
      price: 40000,
      material:"Углепластик",
      category:'Исследования',
      brands:"Rousselet Robatel",
      quantity:1,
    },
    {
      id:7,
      product: "Центрифуга",
      description: "Z-1000Tech",
      produced: "Германия",
      weight: 6,
      price: 30000,
      material:"Сталь",
      category:'Исследования',
      brands:"Rousselet Robatel",
      quantity:1,
    },
    {
      id:8,
      product: "Телескоп",
      description: "Bind-BD5126",
      produced: "Германия",
      weight: 43,
      price: 39000,
      material:"Пластик",
      category:'Анализ',
      brands:"Labor-Microscopes",
      quantity:1,
    },
    {
      id:9,
      product: "Разделительные-цинтрифуга",
      description: "KandanUV-100",
      produced: "Япония",
      weight: 10,
      price: 57000,
      material:"Углепластик",
      category:'Исследования',
      brands:"Flottweg",
      quantity:1,
    }
  ];
  